### ISSUE TITLE
Invalid Syntax - Line 44

### ISSUE THREAD

**Issue by Lerie82** [TheYahya/sherlock#110]
```
(xenial)sunjester@localhost:~/Downloads/sherlock$ python sherlock.py sunjester
  File "sherlock.py", line 44
    Fore.RED + f" {errstr}" +
                          ^
SyntaxError: invalid syntax
```

**Comment by masta2898** [comment]
Wich version of python do u use? f-strings available only after 3.6 version.

**Comment by masta2898** [comment]
@TheYahya I think the author of this issue has already solved his problem.

**Comment by TheYahya** [comment]
Ok, I will close it if @Lerie82 didn't respond.
Thanks @masta2898

**Comment by therealsunjester** [comment]
No the issue wasn't resolved. Python 2.7.12

**Comment by Lerie82** [comment]
Python 2.7.12
