### ISSUE TITLE
Sites sorting

### ISSUE THREAD

**Issue by Czechball** [TheYahya/sherlock#131]
It may be a good idea to sort the sites in sites.md and data.json alphabetically. When I'm looking for sites to add, I always have to Ctrl+F in this repo or just scroll through the file... Also when seeing the results, it's just chaos.

**Comment by TheYahya** [comment]
Yeah, I have same struggle. It's good to sort them.

**Comment by ptalmeida** [comment]
A bit of an addition to this idea, how about adding an option to sort by alexa.com rank?

**Comment by ptalmeida** [comment]
Maybe it should be incorporated into the json data file and updated, per example, with sites_list.py.
