### ISSUE TITLE
Can I have my name in the README as the creator?

### ISSUE THREAD

**Issue by sdushantha** [TheYahya/sherlock#132]
Since I am the creator of Sherlock, could it be possible to have my name or GitHub username in the README? 😄 

**Proof that I am the creator**
First commit is by me: https://github.com/TheYahya/sherlock/commit/b373f81feb3a8eb7a079ebf87b01db4cee1aee97

**Comment by TheYahya** [comment]
Sure @sdushantha, Just add a PR ☺️

**Comment by TheYahya** [comment]
Done at #136
