### ISSUE TITLE
Virustotal error

### ISSUE THREAD

**Issue by Czechball** [TheYahya/sherlock#142]
The [URL used to detect a user on VirusTotal](https://www.virustotal.com/ui/users/username/trusted_users) always results to this:
```
{
    "error": {
        "code": "BadRequestError",
        "message": "Don't be evil"
    }
}
```
I guess they don't like sherlock detecting their users.

**Comment by hoadlck** [comment]
Odd... I typed the request into Chrome, and I got the following:
```json
{
    "data": [],
    "links": {
        "self": "https://www.virustotal.com/ui/users/username/trusted_users?limit=10"
    }
}
```
But, when I type it into Firefox, I get the same thing you got.  But, when I run Sherlock, it does detect things properly.

Are you actually having a problem with Sherlock, or were you just testing with the browser and noticed this?

**Comment by Czechball** [comment]
Okay, I just noticed something very weird. When I opened the link in a regular Chrome window, and being logged in with my account in VirusTotal, I got the error message stating Don't be evil. But when I opened another, anonymous window, and the link in it, it was the same as yours.

**Comment by Czechball** [comment]
Seems like it. And since Sherlock isn't logged in, there is no issue. Closing
