### ISSUE TITLE
[Feature Request] Check Have I Been Pwned

### ISSUE THREAD

**Issue by zero77** [TheYahya/sherlock#163]
Can you please add support for checking have i been pwned. This is a lookup / notification service to see if your email, password or username has been leaked in a data breach.
Thanks

API;
https://haveibeenpwned.com/API/v2

**Comment by crock** [comment]
Not sure if that's the direction the maintainers want to go in. Sherlock is a branding tool used to check username availability.

**Comment by TheYahya** [comment]
`Sherlock` just going to do one job perfectly, for now at least. that could be another library.

**Comment by zero77** [comment]
Thanks for your reply and for considering it.
