### ISSUE TITLE
Method for SnapChat

### ISSUE THREAD

**Issue by sdushantha** [TheYahya/sherlock#177]
I think I have almost got a method to check for Snapchat.

We would have to use this url:
`https://accounts.snapchat.com/accounts/get_username_suggestions`

and with these parameters:
`requested_username=USERNAME&xsrf_token=XSRF_TOKEN_HERE`

**^^After doing a POST requests to this url, you will get some JSON data^^**

**How would we get the `xrsf_token`?**
Here is my ugly method:
```python
import requests
import re

r = requests.get("https://accounts.snapchat.com/accounts/signup?client_id=scan")
cookies = str(r.cookies)
xsrf = re.findall("xsrf_token=(.*?) for", cookies)[0]
```

I do have a problem. Doing this manually is easy (using Burp Suite), but coding it is hard because I keep on getting redirected for some reason. If we could work on this, then it would be very great because Snapchat is a very popular social media platform these days

**Comment by crock** [comment]
You can pass the argument `allow_redirects=False` to the request and that should stop your re-direct loop.

**Comment by sdushantha** [comment]
@crock I tried what you suggested, but I am still not getting the JSON data. 
Here is what I have:
```python
import requests
import re

headers={"User-Agent":"Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0",
        "Referer": "https://accounts.snapchat.com/",
        "content-type": "application/x-www-form-urlencoded; charset=utf-8",
        "origin": "https://accounts.snapchat.com"}

# doing a quick get request to the sign up page so that I can get the xsrf token
r = requests.get("https://accounts.snapchat.com/accounts/signup?client_id=scan",
                headers=headers)

cookies = str(r.cookies)
xsrf = re.findall("xsrf_token=(.*?) for", cookies)[0]

data = {"requested_username":"jmuller8673", "xsrf_token":xsrf}

# just to show what the data payload is
print(data)

# try to fetch the JSON data 
r = requests.post("https://accounts.snapchat.com/accounts/get_username_suggestions", data=data, headers=headers, allow_redirects=False)
```

Do you have an idea on what I might be doing wrong?

**Comment by crock** [comment]
i believe Snapchat web-based registration form uses reCaptcha, so that is going to prevent you from getting the results you need.

**Comment by sdushantha** [comment]
@crock That makes sense. I guess Ill close this issue because I don't think we can go any further with this
