### ISSUE TITLE
Add Testing Infrastructure

### ISSUE THREAD

**Issue by hoadlck** [TheYahya/sherlock#37]
While it is easy to add a new site to scan, it is really hard to know if it is actually supported properly.  Especially for the sites that do not have an explicit error code. For these sites, Sherlock relies on knowing the exact text of the informational page that the social media site presents. Which, even if it works today, could very well break tomorrow.

I am thinking that there would be a `tests` directory that would contain Python code that would run various tests.  The main input to these tests would be a curated list of user names that are supported at a given social media site, and another list of user names that are not.  

- For Each Social Media Site A List Of User Names Supported
Curated list of user names known to be supported.
- For Each Social Media Site A List Of User Names Not Supported
Curated list of user names known to **not** be supported.
- Python Module That Runs Through List And Compares Results To Expected
This would be the code that would run after changes have been made to the module.  And, it would be run before a release was made.

**Comment by naueramant** [comment]
I have taken a swing at it and it seems like some better fragmentation of the sherlock() method is needed to probably write tests.

Would this be something we should gave a go or is testing overkill?

**Comment by hoadlck** [comment]
Yes, I don't see a good way to do this without tearing things up.  And, there has been enough churn that I am worried about slipping it in without dealing with non-trivial merges in the future.

The most minimal change would be to move the open of the JSON file outside of the main routine.  This would allow tests to run against a sub-set of the sites.  I don't think that there will be a username that will be the same across all of the sites.

**Comment by hoadlck** [comment]
I am not done with the testing infrastructure, but one thing that would be useful for test is a list of user names that are valid and user names that are invalid for each site.  The test of each site needs at least one example from each.

Because the full testing infrastructure is going to drive changes to the structure of the code, I am thinking about another way to do this.  But, whichever way we go, we need to get the submitters to do more than just add a new site.

What I am thinking is to add a new command line option to allow the user to call out the specific site that should be checked.  If the option is not on the command line, the the entire list would be ran.

With this option, the test could just be a Python script that called the Sherlock main() routine over and over with different user names and subset of sites.  When a user added a new site, they would also be required to add at least one user that existed and did not exist to the test suite.

Thoughts?

**Comment by TheYahya** [comment]
Sounds good, since it's gonna change the structure of the code, I'm thinking about making `sherlock` a python module that can be import in other codebases and can simply install it with pip even.
I'm working on a local brach now, I haven't decide how to set the structure. but surely after some changes I will make it a `WIP` PR to hear the opinions.

**Comment by hoadlck** [comment]
@TheYahya Pypi support and some restructuring was added in #38, but the pull-request was never merged in.

What I was proposing in #36 (which was not exactly what was implemented) was the following:
```
sherlock/
    .git/
    LICENSE
    README.md
    sites.md
    setup.py
    sherlock/
        __init__.py
        find.py
    tests/
        __init__.py
        release.py
```
The `find.py` would have the search/scan logic that is the heart of the tool.  This would also leave the structure open if other features were added in the future.

I am not sure how the `data.json` file fits into this.  If Sherlock is going to turn into a web application (or have an implementation that runs that way), then storing the information in a database is the way to go.  Maybe there is another directory with the data in it.  When Sherlock starts up (if it is running as a command line tool), it could fetch the latest JSON file from the web.  If it has any problem, it would default to using the last file that it was able to grab (or, in the worst case, the file that shipped with the install).

**Comment by TheYahya** [comment]
The structure is good, for some reasons I prefer keeping tests in `/sherlock` directory:
```
sherlock/
    .git/
    LICENSE
    README.md
    sites.md
    setup.py
    sherlock/
        tests/
            __init__.py
            release.py
        __init__.py
        find.py
```
But it's not that important. 
I think we should put #38  and current codebase together?!
And for the JSON file I think for web application it's good to be a seed file to database.

**Comment by hoadlck** [comment]
I have no problem with putting the tests as a sub-module of sherlock.

Unfortunately, #38 is way out of date.  It would have to be re-implemented.

**Comment by knijam** [comment]
I suggest a way to automate build and testing using **tox** https://tox.readthedocs.io/en/latest/.

**Comment by hoadlck** [comment]
Added some basic testing infrastructure with #127.  I did this change without any of the restructuring that we have talked about.... I am not sure exactly where that is at, and I wanted to get these tests out there so they could help people.

One thing that I do not like about the current way that the tests run is that the working directory gets littered with result files from all of the tests.  I was going to change the main routine around so that the result file was optional, but I did not want to add churn before the restructuring is done.

**Comment by hoadlck** [comment]
With #166, that puts the test coverage at 50% of all sites.  Unfortunately, there are also more sites that we know are not working properly.

**Comment by hoadlck** [comment]
With #169, that puts the test coverage at 100%!

Issues that exist with tests at the current time:
- Some of the sites are randomly intermittent, and we get failures because Sherlock could not connect to them.  
- The tests hang up because some site is not responding.  
- Sites like AngelList which interpret the Sherlock queries coming from one IP address as some kind of bot activity.
- Tor options are not tested.
- Proxy options are not tested.

But, this is a good first pass.  Any restructuring that we do in the future will have a complete test of site connections available.

There can be other issues added in the future to add more sophisticated options to the testing, but I think that this issue can be closed now.
