### ISSUE TITLE
syntax erroe

### ISSUE THREAD

**Issue by WhiteDevil2002** [TheYahya/sherlock#42]
there is a syntax error in the file sherlock.py in line 17.
please review.
thank you!

**Comment by sdushantha** [comment]
I just ran Sherlock and got no error. Try cloning the repo again and run it again. Because I did merge a PR a few hours ago and that might have fixed that syntax error. Make sure that you are using Python 3.6 or higher

**Comment by svisser** [comment]
It might be good to check that merge because the change in #8 is now no longer there (and perhaps others as well).

**Comment by hoadlck** [comment]
I added "enforce utf-8 encoding when we open data.json" (#8) back in.  I
tried looking thru the merge, and did not find anything else.  But, the
parallel queries really changed the structure, so I am not confident.

**Comment by noviluni** [comment]
That happened to me when I tried to execute the script with python 2.7

**Comment by hoadlck** [comment]
Only Python 3.6+ is supported.  Python 2.7 will not work.

**Comment by jcs090218** [comment]
@WhiteDevil2002 Is this issue fixed? If fixed, can we close this?

**Comment by hoadlck** [comment]
I think that this issue has been addressed. Pretty sure that it was caused by running Sherlock with Python 2.7.  In any case, there has been quite a bit of development since this issue was entered, and any past problem would be completely changed by now.

But, please reopen if still relevant.
