### ISSUE TITLE
Looking for a new owner for Sherlock

### ISSUE THREAD

**Issue by sdushantha** [TheYahya/sherlock#54]
I can't really manage this repo anymore. So if there is anyone who wants to get the ownership of this repo please let me know.

**Comment by sdushantha** [comment]
@nareddyt @shijuleon @cblument @cclauss @anto-christo @MagicFab @svisser boardens @ronaldseoh @aggiebill rajdeepbharati

**Comment by anto-christo** [comment]
Hi @sdushantha, I personally feel not quite eligible to maintain this repo. I'm mainly a JavaScript developer and have very less experience with Python. I'm still a beginner at it. 
I'd not prefer taking ownership for the good of the project but I'll be glad to co-maintain if someone more experienced with Python and OSS is ready to lead. Thank you.

**Comment by nareddyt** [comment]
Congrats @TheYahya 🥇

Feel free to @mention me or message me if you need any help reviewing PRs or finding fixes for issues!

**Comment by TheYahya** [comment]
Thanks @nareddyt, Sure, I would like to use your help.
