### ISSUE TITLE
Add common domains

### ISSUE THREAD

**Issue by ptalmeida** [TheYahya/sherlock#58]
I think this tool is great for someone looking to create a new internet personna or company, so maybe it would be a logical addition to add a search for .com and .net domains, per example.

**Comment by naueramant** [comment]
Seems like a new project which maybe uses sherlock as a module?

**Comment by ptalmeida** [comment]
Here's a mockup of what could be added:

first, run:
`pip3 install python-whois`

at the top of sherlock.py, add:
`import whois`

in the method scherlock, 

    extensions = ['.com','.net','.me','.info']
    for ext in extensions:

        domain = username + ext
        try:
            w = whois.whois(domain)       
            if w.status == None:
                print("\033[37;1m[\033[91;1m-\033[37;1m]\033[92;1m {}:\033[93;1m Not Found!".format(ext))
            else:
                print("\033[37;1m[\033[92;1m+\033[37;1m]\033[92;1m {}:\033[0m".format(ext), domain)
                write_to_file(domain, fname)
        except whois.parser.PywhoisError as e:
            print("\033[37;1m[\033[91;1m-\033[37;1m]\033[92;1m {}:\033[93;1m Error!".format(ext))
