### ISSUE TITLE
requests has no attribute '__description__'

### ISSUE THREAD

**Issue by suthree** [TheYahya/sherlock#63]
requests == 2.13.0  
requests has no attribute `__description__`
instead only has
```
  '__author__',
  '__build__',
  '__builtins__',
 '__cached__',
 '__copyright__',
 '__doc__',
 '__file__',
 '__license__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__title__',
 '__version__',
 '_internal_utils',
```
so i use the  `__doc__`
am i right? 
Thank you

**Comment by rajdeepbharati** [comment]
requests==2.18.4 does have attribute `__description__`

Use the latest version of requests, install it using the requirements.txt file

**Comment by Eurus-Holmes** [comment]
@rajdeepbharati I have installed the requests==2.20.1, but the error still exists...
<img width="1132" alt="2019-01-05 1 17 45" src="https://user-images.githubusercontent.com/34226570/50720681-540d6100-10ec-11e9-8f32-37eb0504aa3c.png">

the error:
```shell
Traceback (most recent call last):
  File "sherlock.py", line 379, in <module>
    main()
  File "sherlock.py", line 301, in main
    f"{requests.__description__}:  {requests.__version__}\n" + \
AttributeError: module 'requests' has no attribute '__description__'
```

**Comment by rajdeepbharati** [comment]
@Eurus-Holmes Perhaps you used the wrong version of python. Can you install a `virtualenv` and try again. Although this line isn't really important for sherlock to work.
This is what `requests.__description__` is: `'Python HTTP for Humans.'`

**Comment by Eurus-Holmes** [comment]
@rajdeepbharati oh, thanks, It works when I used a virtualenv environment.

**Comment by rajdeepbharati** [comment]
@TheYahya I think this issue may be closed

**Comment by 7amod** [comment]
How can i use the virtualen environment?
