### ISSUE TITLE
Add the project on docker hub

### ISSUE THREAD

**Issue by guillaumebriday** [TheYahya/sherlock#74]
Hey !

Could you add a webhook to the docker hub to automatically build the image on the cloud and make it available without cloning the project ?

I can't do it for you in a PR, I'm sorry !

Thank you for your work 👍

**Comment by nareddyt** [comment]
@TheYahya do you have a dockerhub account? It would make sense to have you do it, as you own the repo currently.

If not, I can set it up, but it would be under `nareddyt/`

**Comment by TheYahya** [comment]
Great idea @guillaumebriday 
Yes @nareddyt, I done it at #84
