### ISSUE TITLE
Display response times in verbose mode

### ISSUE THREAD

**Issue by nareddyt** [TheYahya/sherlock#82]
## Feature Request

It would be nice to display the response time for each request. 

### Why?

- It would help us determine which sites cause the program to slow down. If a site is very slow and non-critical, we could remove it to speed up Sherlock.
- The more metrics the merrier! Has very little overhead, so why not :)

### User Experience

We would only display this information in verbose mode (`-v` flag). The information can be displayed in each output line as:

```txt
[+] [78 ms] Quora: https://www.quora.com/profile/nareddyt
```

Furthermore, these response times can be exported in the CSV.

### Implementation Details

We would just need to store the time reach request was created in the `net_info` or `results_site` dictionaries. Then when the request is done, we would note the end time.

Note there is some math involved in calculating times. It's not a simple `end-start` because the `result` for each response is extracted in the order of requests (not as soon as a request finishes). This is something I still need to think about...

**Comment by Czechball** [comment]
Sounds good. Maybe then we could sorts the sites by their response time and check the fastest ones first.

**Comment by TheYahya** [comment]
Seems great @nareddyt, can't wait to use it ☺️
