### ISSUE TITLE
The install script only works on Debian based Linux distros

### ISSUE THREAD

**Issue by sdushantha** [TheYahya/sherlock#87]
There is a bash [script](https://github.com/TheYahya/sherlock/blob/master/install_packages.sh) which installs all of the packages automatically and that is great! But there is one drawback though, it wont work in Arch based distros (Manjaro, ArchLabs, etc). That is because those distros use `pacman` instead of `apt` to download the packages.

 In my opinion, I dont think that it is good idea to have that script unless we add support to other distros as well.

**Comment by nareddyt** [comment]
@theodosisathanasakis

**Comment by theodosisathanasakis** [comment]
I din't think that. Let me give it a try for the basic distos and I'll let you know.

**Comment by tdh8316** [comment]
> I din't think that. Let me give it a try for the basic distos and I'll let you know.

@sdushantha is right. Actually, we don't need to use the install script. (If it's required for them, you need to write an installation script for each distribution.

Fedora: Yum(DNF)
OpenSuse: Zypper
Arch: Pacman
And etc...

**Comment by sdushantha** [comment]
Just a note, I dont think everyone wants to download the dependencies globally. Some might want to download them locally.

**Global Install**

```pip3 install xyz```

**Local Install**

```pip3 install --user xyz```

**Comment by theodosisathanasakis** [comment]
> Just a note, I dont think everyone wants to download the dependencies globally. Some might want to download them locally.

Ok, so do you want me to add a question before "_pip3 install_" commands.

**Comment by sdushantha** [comment]
@theodosisathanasakis 
Yeah, that would be nice

**Comment by theodosisathanasakis** [comment]
I think this issue has been solved as #92 is merged to master.

**Comment by nareddyt** [comment]
Closed by #92
